include: package:lints/recommended.yaml

analyzer:
  errors:
    missing_required_param: error
    missing_return: error
    unused_import: error
    unused_local_variable: error
    dead_code: error
  language:
    strict-casts: true
    strict-raw-types: true
