name: money
description: A currency formatting utility
version: 0.2.0
homepage: https://github.com/jogboms/money.dart

environment:
  sdk: ">=2.12.0 <4.0.0"

funding:
  - https://www.paypal.me/jogboms
  - https://www.buymeacoffee.com/jogboms

dependencies:
  meta: ">=1.8.0 <2.0.0"
  intl: ">=0.18.1 <1.0.0"

dev_dependencies:
  lints: ^4.0.0
  test: ^1.25.8
  coverage: ^1.9.2
