name: money
description: A currency formatting utility
version: 0.1.0
homepage: https://github.com/jogboms/money.dart

environment:
  sdk: ">=2.12.0 <3.0.0"

funding:
  - https://www.paypal.me/jogboms
  - https://www.buymeacoffee.com/jogboms

dependencies:
  meta: ^1.8.0
  intl: ^0.18.1

dev_dependencies:
  lints: ^2.0.1
  test: ^1.24.0
  coverage: ^1.6.3
